// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qribbiabkoorfsvzqbcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyaWJiaWFia29vcmZzdnpxYmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzIxNzcsImV4cCI6MjA2NjkwODE3N30.Sty5ybgtT3nQDnsI4nl8SECB-ataaSRj3pHCut9Btv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});